using System.Text;
using System.Text.RegularExpressions;
using CompanyHarness.Contracts;

namespace CompanyHarness.Desktop.Core.Runtime;

public static partial class HarnessCompanyPatchWriter
{
    public static async Task<string> WriteAsync(
        string applicationDataRoot,
        ModelCatalogResponse catalog,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(applicationDataRoot);
        Validate(catalog);

        Directory.CreateDirectory(applicationDataRoot);
        var path = Path.Combine(applicationDataRoot, "company.cordis.yml");
        var temporaryPath = path + ".tmp";
        await File.WriteAllTextAsync(temporaryPath, Render(catalog), new UTF8Encoding(false), cancellationToken);
        File.Move(temporaryPath, path, true);
        return path;
    }

    internal static string Render(ModelCatalogResponse catalog)
    {
        var searchModel = catalog.Models.Any(model => model.Id == "deepseek-v4-flash")
            ? "deepseek-v4-flash"
            : catalog.DefaultModel;
        var builder = new StringBuilder($$"""
            # Generated by Company Harness. No credentials are stored in this file.
            - id: agent-default-model
              config:
                provider: deepseek-official
                model: {{Yaml(catalog.DefaultModel)}}

            - id: llm-deepseek
              config:
                apiKeyEnv: DEEPSEEK_API_KEY
                baseURL: !!js process.env.DEEPSEEK_BASE_URL
                thinking: enabled
                reasoningEffort: high
                maxTokens: 65536
                defaultContextWindow: 1000000
                models:
            """);
        builder.AppendLine();
        foreach (var model in catalog.Models)
        {
            builder.AppendLine($"      - id: {Yaml(model.Id)}");
            builder.AppendLine($"        name: {Yaml(model.Name)}");
            builder.AppendLine($"        description: {Yaml(model.Description)}");
            builder.AppendLine("        contextWindow: 1000000");
            builder.AppendLine("        maxTokens: 65536");
            if (model.InputModalities.Contains("image", StringComparer.Ordinal))
            {
                builder.AppendLine("        inputModalities: [text, image]");
            }
        }
        builder.Append($$"""

            - id: web-search-deepseek
              config:
                apiKeyEnv: DEEPSEEK_API_KEY
                baseURL: !!js process.env.DEEPSEEK_SEARCH_BASE_URL
                model: {{Yaml(searchModel)}}
                maxTokens: 4096
                maxUses: 5

            - id: llm-pi-ai
              disabled: true
            - id: ui-settings-models
              disabled: true
            - id: ui-settings-plugins
              disabled: true
            - id: session-telemetry-otel
              disabled: true
            """);
        return builder.ToString();
    }

    private static void Validate(ModelCatalogResponse catalog)
    {
        if (catalog.Models is null || catalog.Models.Count == 0)
            throw new InvalidOperationException("公司策略没有可用模型。");
        if (!catalog.Models.Any(model => model.Id == catalog.DefaultModel))
            throw new InvalidOperationException("公司默认模型不在可用目录中。");
        foreach (var model in catalog.Models)
        {
            if (!ModelIdPattern().IsMatch(model.Id)
                || string.IsNullOrWhiteSpace(model.Name)
                || model.Name.Length > 128
                || string.IsNullOrWhiteSpace(model.Description)
                || model.Description.Length > 512
                || model.InputModalities.Any(value => value is not ("text" or "image")))
                throw new InvalidOperationException("服务器返回了无效的模型目录。");
        }
    }

    private static string Yaml(string value) => $"'{value.Replace("'", "''")}'";

    [GeneratedRegex("^[a-z0-9][a-z0-9._-]{0,127}$", RegexOptions.CultureInvariant)]
    private static partial Regex ModelIdPattern();
}
